Repository Los-Terremotos/GreenPets, pull requests merged in 2024-04, with the labels that each got.

#109 42/FE- Results Modals
  client/src/__generated__/gql.ts
  client/src/__generated__/graphql.ts
  client/src/components/FeatureCard.tsx
  client/src/components/ResultsPageComponents/ContentTabs.tsx
  client/src/components/ResultsPageComponents/ResultsDetailCard.tsx
  client/src/components/ResultsPageComponents/TabDataMapping.tsx
  client/src/components/ResultsPageComponents/ViewMore.tsx
  client/src/utils/fetchCareGuides.tsx
  client/src/utils/formatTitles.tsx
  client/types.ts
  server/graphql.schema.json
  server/src/models.ts
  server/src/schema.ts
  server/src/types.ts
Labels: enhancement

#114 18/FS-Unit Testing
  .gitignore
  _daily_logs/CORS links notes for production
  _daily_logs/March_logs.md
  _daily_logs/Plant.ApiResponsev2.js
  _daily_logs/PlantApiResponse.html
  _daily_logs/PlantApiResponsev2.js
  _daily_logs/examples/MockDataServer.md
  _daily_logs/examples/ReviewCard Example.jpg
  _daily_logs/group_logs.md
  _daily_logs/kp_logs.md
  _daily_logs/matt_log.md
  _daily_logs/production.md
  _daily_logs/production_notes.md
  _daily_logs/testing_notes.md
  client/.eslintrc.cjs
  client/__tests__/HomePage.test.tsx
  client/__tests__/Navbar.test.tsx
  client/__tests__/__mocks__/fileMock.js
  client/jest.config.ts
  client/package-lock.json
  client/package.json
  client/rollup.config.js
  client/src/Features/QueryResult/queryResultSlice.ts
  client/src/components/HomePageSections/AboutSection.tsx
  client/src/components/HomePageSections/CallToActionSection.tsx
  client/src/components/HomePageSections/FooterSection.tsx
  client/src/components/HomePageSections/HeroSection.tsx
  client/src/components/HomePageSections/ReviewSection.tsx
  client/src/components/HomePageSections/SliderSection.tsx
  client/src/components/Navbar.tsx
  client/src/components/NavbarComponents/UnstyledNavbar.tsx
  client/src/components/Questions.tsx
  client/src/components/ResultsPageComponents/Results.tsx
  client/src/components/ResultsPageComponents/ViewMore.tsx
  client/src/components/ReviewCard.tsx
  client/src/pages/HomePage.tsx
  client/src/utils/fetchCareGuides.tsx
  client/tsconfig.json
  client/tsconfig.test.json
  server/__tests__/index.test.ts
  server/src/types.ts
Labels: enhancement

#116 18/Deployment-bug
  _daily_logs/kp_logs.md
  client/declarations.d.ts
  client/src/components/ResultsPageComponents/ContentTabs.tsx
  client/src/utils/fetchCareGuides.tsx
  client/tsconfig.json
  server/src/index.ts
  server/src/routers/apiRouter.ts
Labels: bug

#118 Adjusted case sensitivity for mocking Navbar component
  client/__tests__/HomePage.test.tsx
Labels: bug

#119 Homepage Mobile Styling
  client/index.html
  client/package-lock.json
  client/src/App/store.ts
  client/src/Features/Navbar/hamburgerOpen 2.ts
  client/src/Features/Navbar/hamburgerOpen.ts
  client/src/components/ContributorCard.tsx
  client/src/components/FlipCard.tsx
  client/src/components/HomePageSections/AboutSection.tsx
  client/src/components/HomePageSections/CallToActionSection.tsx
  client/src/components/HomePageSections/ContributionSection.tsx
  client/src/components/HomePageSections/FeaturesSection.tsx
  client/src/components/HomePageSections/FooterSection.tsx
  client/src/components/HomePageSections/HeroSection.tsx
  client/src/components/HomePageSections/ReviewSection.tsx
  client/src/components/HomePageSections/Roadmap.tsx
  client/src/components/Navbar.tsx
  client/src/components/ReviewCard.tsx
  client/src/components/RoadmapCard.tsx
  client/src/index.css
  client/src/pages/HomePage.tsx
  package.json
  server/package-lock.json
Labels: bug

#121 Spring Update V.13
  client/__tests__/HomePage.test.tsx
  client/index.html
  client/package-lock.json
  client/package.json
  client/src/App/store.ts
  client/src/Features/Navbar/hamburgerOpen 2.ts
  client/src/Features/Navbar/hamburgerOpen.ts
  client/src/components/ContributorCard.tsx
  client/src/components/FlipCard.tsx
  client/src/components/HomePageSections/AboutSection.tsx
  client/src/components/HomePageSections/CallToActionSection.tsx
  client/src/components/HomePageSections/ContributionSection.tsx
  client/src/components/HomePageSections/FeaturesSection.tsx
  client/src/components/HomePageSections/FooterSection.tsx
  client/src/components/HomePageSections/HeroSection.tsx
  client/src/components/HomePageSections/ReviewSection.tsx
  client/src/components/HomePageSections/Roadmap.tsx
  client/src/components/Navbar.tsx
  client/src/components/ReviewCard.tsx
  client/src/components/RoadmapCard.tsx
  client/src/index.css
  client/src/pages/HomePage.tsx
  package.json
  server/package-lock.json
  server/package.json
Labels: bug

#122 Update deploy-to-production.yml
  .github/workflows/deploy-to-production.yml
Labels: enhancement

#123 18/FS-Unit_Testing
  _daily_logs/testing_notes.md
  client/__tests__/Navbar.test.tsx
  client/package-lock.json
  client/package.json
Labels: documentation

#124 Synced package-lock.json with package.json files
  client/package-lock.json
  server/package-lock.json
Labels: bug
